13-phoenix/chirp/lib/chirp_web/router.ex
defmodule ChirpWeb.Router do
  use ChirpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ChirpWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChirpWeb do
    pipe_through :browser

    live "/", PageLive, :index
    
    live "/posts", PostLive.Index, :index
    live "/posts/new", PostLive.Index, :new
    live "/posts/:id/edit", PostLive.Index, :edit

    live "/posts/:id", PostLive.Show, :show
    live "/posts/:id/show/edit", PostLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChirpWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChirpWeb.Telemetry
    end
  end
end

13-phoenix/chirp/lib/chirp_web/live/live_helpers.ex
defmodule ChirpWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `ChirpWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, ChirpWeb.PostLive.FormComponent,
        id: @post.id || :new,
        action: @live_action,
        post: @post,
        return_to: Routes.post_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, ChirpWeb.ModalComponent, modal_opts)
  end
end

13-phoenix/chirp/lib/chirp_web/live/modal_component.ex
defmodule ChirpWeb.ModalComponent do
  use ChirpWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

13-phoenix/chirp/lib/chirp_web/live/page_live.ex
defmodule ChirpWeb.PageLive do
  use ChirpWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not ChirpWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

13-phoenix/chirp/lib/chirp_web/live/post_live/form_component.ex
defmodule ChirpWeb.PostLive.FormComponent do
  use ChirpWeb, :live_component

  alias Chirp.Timeline

  @impl true
  def update(%{post: post} = assigns, socket) do
    changeset = Timeline.change_post(post)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"post" => post_params}, socket) do
    changeset =
      socket.assigns.post
      |> Timeline.change_post(post_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"post" => post_params}, socket) do
    save_post(socket, socket.assigns.action, post_params)
  end

  defp save_post(socket, :edit, post_params) do
    case Timeline.update_post(socket.assigns.post, post_params) do
      {:ok, _post} ->
        {:noreply,
         socket
         |> put_flash(:info, "Post updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_post(socket, :new, post_params) do
    case Timeline.create_post(post_params) do
      {:ok, _post} ->
        {:noreply,
         socket
         |> put_flash(:info, "Post created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

13-phoenix/chirp/lib/chirp_web/live/post_live/index.ex
defmodule ChirpWeb.PostLive.Index do
  use ChirpWeb, :live_view

  alias Chirp.Timeline
  alias Chirp.Timeline.Post

  @impl true
  def mount(_params, _session, socket) do
    if connected?(socket), do: Timeline.subscribe()
    {:ok, assign(socket, :posts, list_posts()), temporary_assigns: [posts: []]}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Post")
    |> assign(:post, Timeline.get_post!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Post")
    |> assign(:post, %Post{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Posts")
    |> assign(:post, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    post = Timeline.get_post!(id)
    {:ok, _} = Timeline.delete_post(post)

    {:noreply, assign(socket, :posts, list_posts())}
  end

  def handle_info({:post_created, post}, socket) do
    {:noreply, update(socket, :posts, fn posts -> [post | posts] end)}
  end

  def handle_info({:post_updated, post}, socket) do
    {:noreply, update(socket, :posts, fn posts -> [post | posts] end)}
  end

  defp list_posts do
    Timeline.list_posts()
  end
end

13-phoenix/chirp/lib/chirp_web/live/post_live/post_component.ex
defmodule ChirpWeb.PostLive.PostComponent do
  use ChirpWeb, :live_component

  alias Chirp.Timeline
  alias Chirp.Timeline.Post

  def render(assigns) do
    ~L"""
    <div id="post-<%= @post.id %>" class="card">
      <div class="card-content">
        <div  class="row">
          <div class="col xs3">
            <div>
              <img src="http://lorempixel.com/60/60" />
            </div>
          </div>
          <div class="col xs9">
            <b>@<%= @post.username %></b>
            <br/>
            <%= @post.body %>
          </div>
        </div>
        <div class="card-title activator grey-text text-darken-4 row">
          <span class="col col-s3">
            <%= live_patch to: Routes.post_index_path(@socket, :edit, @post) do %>
              <i class="material-icons">create</i>
            <% end %>
          </span>
          <span class="col col-s3">
            <%= link to: "#", phx_click: "delete", phx_value_id: @post.id, data: [confirm: "Are you sure?"] do %>
              <i class="material-icons">delete</i>
            <% end %>
          </span>
          <span class="col col-s3">
            <a href="#" phx-click="like" phx-target="<%= @myself %>">
              <%= @post.like_count %>
              <i class="material-icons">thumb_up</i>
            </a>
          </span>
          <span class="col col-s3">
            <a href="#" phx-click="report" phx-target="<%= @myself %>">
              <%= @post.reports_count %>
              <i class="material-icons">not_interested</i>
            </a>
          </span>
        </div>
      </div>
    </div>
    """
  end

  def handle_event("like", _, socket) do
    Chirp.Timeline.inc_likes(socket.assigns.post)
    {:noreply, socket}
  end

  def handle_event("report", _, socket) do
    Chirp.Timeline.inc_reports(socket.assigns.post)
    {:noreply, socket}
  end
end

13-phoenix/chirp/lib/chirp_web/live/post_live/show.ex
defmodule ChirpWeb.PostLive.Show do
  use ChirpWeb, :live_view

  alias Chirp.Timeline

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:post, Timeline.get_post!(id))}
  end

  defp page_title(:show), do: "Show Post"
  defp page_title(:edit), do: "Edit Post"
end

13-phoenix/chirp/lib/chirp_web/live/post_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "post-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <!--
  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= error_tag f, :username %>
  -->

  <%= label f, :body %>
  <!--
  <%= text_input f, :body %>
  -->
  <%= textarea f, :body %>
  <%= error_tag f, :body %>

  <!--
  <%= label f, :like_count %>
  <%= number_input f, :like_count %>
  <%= error_tag f, :like_count %>

  <%= label f, :reports_count %>
  <%= number_input f, :reports_count %>
  <%= error_tag f, :reports_count %>
  -->

  <%= submit "Post", phx_disable_with: "Posting..." %>
</form>

13-phoenix/chirp/lib/chirp_web/live/post_live/index.html.leex
<h1>Timeline</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, ChirpWeb.PostLive.FormComponent,
    id: @post.id || :new,
    title: @page_title,
    action: @live_action,
    post: @post,
    return_to: Routes.post_index_path(@socket, :index) %>
<% end %>

<!--
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Body</th>
      <th>Like count</th>
      <th>Reports count</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="posts">
    <%= for post <- @posts do %>
      <tr id="post-<%= post.id %>">
        <td><%= post.username %></td>
        <td><%= post.body %></td>
        <td><%= post.like_count %></td>
        <td><%= post.reports_count %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.post_show_path(@socket, :show, post) %></span>
          <span><%= live_patch "Edit", to: Routes.post_index_path(@socket, :edit, post) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: post.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
-->


<div id="posts" phx-update="prepend">
  <%= for post <- @posts do %>
    <%= live_component @socket, ChirpWeb.PostLive.PostComponent, id: post.id, post: post  %>
  <% end %>
</div>
<span><%= live_patch "Post something for your friend", to: Routes.post_index_path(@socket, :new) %></span>

13-phoenix/chirp/lib/chirp_web/live/post_live/show.html.leex
<h1>Show Post</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, ChirpWeb.PostLive.FormComponent,
    id: @post.id,
    title: @page_title,
    action: @live_action,
    post: @post,
    return_to: Routes.post_show_path(@socket, :show, @post) %>
<% end %>

<ul>

  <li>
    <strong>Username:</strong>
    <%= @post.username %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @post.body %>
  </li>

  <li>
    <strong>Like count:</strong>
    <%= @post.like_count %>
  </li>

  <li>
    <strong>Reports count:</strong>
    <%= @post.reports_count %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.post_show_path(@socket, :edit, @post), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.post_index_path(@socket, :index) %></span>